version: "3.7"

services:
  flask:
    build: ./flask
    container_name: lizeyan_flask
    restart: always
    ports:
      - 8080:5000

  nginx:
    build: ./nginx
    container_name: lizeyan_nginx
    restart: always
    ports:
      - "80:80"
